-
  name: Create an EC2 Instance
  hosts: localhost
  vars_files:
    - aws_variables
  tasks:
    - name: Launch EC2 Instance using ansible
      ec2:
        key_name: "{{ key_name }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ aws_region }}"
        image: "{{ image_id }}"
        instance_type: "{{ instance_type }}"
        count: 1
        wait: yes
        group_id: "{{ security_group_id }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        assign_public_ip: yes
      register: ec2
    
    - name: displaying the created instances
      debug: 
        msg:
          - "Created Instance Id {{ item.public_ip }}"
      with_items: "{{ ec2.instances }}"
    
    - name: Add new instance to host group
      add_host: 
        hostname: "{{ item.public_ip }}"
        groupname: aws_ec2
      loop: "{{ ec2.instances }}"
    
    - name: Wait for instance to come up
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection: 
        delay: 60
        timeout: 300
      loop: "{{ ec2.instances }}"

-
  name: Install httpd web services
  hosts: aws_ec2
  become: True
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present
    - name: start httpd service
      service:
        name: httpd
        state: started
    - name: enable httpd service
      service:
        name: httpd
        enabled: yes
    - name: Copy the sample web page to html direcotry
      copy:
        src: /tmp/web_application.yaml
        dest: /var/www/html/
